SITE_PROFILES = {
    "amazon_in": {
        "name": "Amazon India",
        "url": "https://www.amazon.in",
        "search_url_template": "https://www.amazon.in/s?k={query}",
        "search_input_selectors": ["#twotabsearchtextbox", "input[name='field-keywords']"],
        "product_selectors": [".s-result-item[data-component-type='s-search-result']"],
        "title_selectors": ["h2 a span", "h2 span"],
        "link_selectors": ["h2 a", "a.a-link-normal.s-no-outline"],
        "price_selectors": [".a-price .a-offscreen", ".a-price-whole"],
    },
    "amazon_com": {
        "name": "Amazon US",
        "url": "https://www.amazon.com",
        "search_url_template": "https://www.amazon.com/s?k={query}",
        "search_input_selectors": ["#twotabsearchtextbox", "input[name='field-keywords']"],
        "product_selectors": [".s-result-item[data-component-type='s-search-result']"],
        "title_selectors": ["h2 a span", "h2 span"],
        "link_selectors": ["h2 a", "a.a-link-normal.s-no-outline"],
        "price_selectors": [".a-price .a-offscreen", ".a-price-whole"],
    },
    "flipkart": {
        "name": "Flipkart",
        "url": "https://www.flipkart.com",
        "search_url_template": "https://www.flipkart.com/search?q={query}",
        "search_input_selectors": ["input[name='q']", "input[title='Search for products, brands and more']"],
        "product_selectors": ["div[data-id]", "div._75nlfW"],
        "title_selectors": ["a[title]", "div.KzDlHZ", "a.wjcEIp"],
        "link_selectors": ["a[href*='/p/']", "a.CGtC98", "a.wjcEIp"],
        "price_selectors": ["div.Nx9bqj", "div._30jeq3"],
    },
    "ebay": {
        "name": "eBay",
        "url": "https://www.ebay.com",
        "search_url_template": "https://www.ebay.com/sch/i.html?_nkw={query}",
        "search_input_selectors": ["#gh-ac", "input[type='text'][name='_nkw']"],
        "product_selectors": [".srp-results .s-item"],
        "title_selectors": [".s-item__title"],
        "link_selectors": [".s-item__link"],
        "price_selectors": [".s-item__price"],
    },
    "walmart": {
        "name": "Walmart",
        "url": "https://www.walmart.com",
        "search_url_template": "https://www.walmart.com/search?q={query}",
        "search_input_selectors": ["input[aria-label='Search']", "input[type='search']"],
        "product_selectors": ["[data-item-id]", "[data-testid='list-view'] [role='listitem']"],
        "title_selectors": ["[data-automation-id='product-title']", "a span"],
        "link_selectors": ["a[href*='/ip/']", "a[data-testid='product-title']"],
        "price_selectors": ["[itemprop='price']", "[data-automation-id='product-price']"],
    },
    "bestbuy": {
        "name": "Best Buy",
        "url": "https://www.bestbuy.com",
        "search_url_template": "https://www.bestbuy.com/site/searchpage.jsp?st={query}",
        "search_input_selectors": ["#gh-search-input", "input[type='search']"],
        "product_selectors": [".sku-item"],
        "title_selectors": [".sku-title a", "h4 a"],
        "link_selectors": [".sku-title a"],
        "price_selectors": [".priceView-customer-price span", ".pricing-price__range"],
    },
}

SITE_ALIASES = {
    "amazon": "amazon_in",
    "amazon.in": "amazon_in",
    "amazon india": "amazon_in",
    "amazon us": "amazon_com",
    "amazon.com": "amazon_com",
    "flipkart": "flipkart",
    "ebay": "ebay",
    "walmart": "walmart",
    "bestbuy": "bestbuy",
    "best buy": "bestbuy",
}
